-- ============================================================================
--  Bookstore Manager — full schema (offline-first, UUID keys)
--  Run this once in the Supabase SQL editor.
--
--  This REPLACES the old bigserial schema. It drops the existing tables, so
--  only run it on a project whose data you are happy to lose.
--
--  Why UUIDs: a till that is offline has to create books, sales and customers
--  without the server, so the client mints the id itself. A bigserial column
--  cannot do that — two offline rows would both claim the same number.
-- ============================================================================

-- ---------------------------------------------------------------- reset ----
drop table if exists purchases cascade;
drop table if exists sales cascade;
drop table if exists books cascade;
drop table if exists suppliers cascade;
drop table if exists customers cascade;
drop table if exists settings cascade;

-- --------------------------------------------------------------- books -----
create table books (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid(),
  title         text not null,
  author        text,
  isbn          text,
  category      text,
  cost          numeric not null default 0,
  price         numeric not null default 0,
  stock         integer not null default 0,
  reorder_level integer default 3,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ----------------------------------------------------------- suppliers -----
create table suppliers (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid(),
  name       text not null,
  contact    text,
  phone      text,
  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------- customers -----
create table customers (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid(),
  name       text not null,
  phone      text,
  email      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------- purchases -----
create table purchases (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid(),
  supplier_id   uuid references suppliers(id) on delete set null,
  book_id       uuid references books(id) on delete set null,
  book_title    text,
  qty           integer not null,
  cost_each     numeric not null,
  purchase_date timestamptz not null default now(),
  notes         text,
  updated_at    timestamptz not null default now()
);

-- --------------------------------------------------------------- sales -----
-- receipt_no is text and is generated by the client, so a sale rung up with no
-- connection still gets its number. Unique per user so a replayed outbox can
-- never quietly overwrite an earlier receipt.
create table sales (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid(),
  receipt_no  text not null,
  sale_date   timestamptz not null default now(),
  customer    text,
  phone       text,
  customer_id uuid references customers(id) on delete set null,
  items       jsonb not null default '[]'::jsonb,
  subtotal    numeric not null default 0,
  disc_type   text,
  disc_input  numeric not null default 0,
  disc_pct    numeric not null default 0,
  disc_amt    numeric not null default 0,
  tax_pct     numeric not null default 0,
  tax_amt     numeric not null default 0,
  total       numeric not null default 0,
  payment     text,
  updated_at  timestamptz not null default now(),
  constraint sales_receipt_no_unique unique (user_id, receipt_no)
);

-- ------------------------------------------------------------ settings -----
create table settings (
  user_id      uuid primary key default auth.uid(),
  store_name   text default 'My Bookstore',
  phone        text default '',
  address      text default '',
  footer       text default 'Thank you for your purchase!',
  currency     text default 'Rs.',
  receipt_size text default 'thermal',
  logo         text default '',
  updated_at   timestamptz not null default now()
);

-- --------------------------------------------------------------- index -----
create index books_user_idx      on books (user_id);
create index sales_user_date_idx on sales (user_id, sale_date desc);
create index purchases_user_idx  on purchases (user_id, purchase_date desc);
create index customers_user_idx  on customers (user_id);
create index suppliers_user_idx  on suppliers (user_id);

-- ----------------------------------------------------------- updated_at ----
-- Every write stamps updated_at. The sync engine reads it to decide which copy
-- of a row is newer when the same row was touched in two places.
create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger books_touch      before update on books      for each row execute function touch_updated_at();
create trigger suppliers_touch  before update on suppliers  for each row execute function touch_updated_at();
create trigger customers_touch  before update on customers  for each row execute function touch_updated_at();
create trigger purchases_touch  before update on purchases  for each row execute function touch_updated_at();
create trigger sales_touch      before update on sales      for each row execute function touch_updated_at();
create trigger settings_touch   before update on settings   for each row execute function touch_updated_at();

-- ------------------------------------------------------------------ RLS ----
alter table books      enable row level security;
alter table suppliers  enable row level security;
alter table customers  enable row level security;
alter table purchases  enable row level security;
alter table sales      enable row level security;
alter table settings   enable row level security;

create policy "own books"     on books     for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own suppliers" on suppliers for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own customers" on customers for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own purchases" on purchases for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own sales"     on sales     for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own settings"  on settings  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
